name: Run Pytest with HTML and PDF Reports

on:
  push:
    branches:
      - feature-deployment
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate HTML report
      run: |
        pytest --html=report.html
        pytest

    - name: Generate PDF report
      run: |
        python pdf_generator.py

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: report.html

    - name: Upload PDF report
      uses: actions/upload-artifact@v3
      with:
        name: pdf-report
        path: report.pdf
