name: Run Pytest with HTML and PDF Reports

on:
  push:
    branches:
      - feature-deployment
  pull_request:
    branches:
      - main

jobs:
  test-python:
    name: Test con Python
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate HTML report
      run: |
        pytest --html=report.html --self-contained-html
        pytest

    - name: Generate PDF report
      run: |
        python pdf_generator.py

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: report.html

    - name: Upload PDF report
      uses: actions/upload-artifact@v3
      with:
        name: pdf-report
        path: report.pdf

  test-java-maven:
    name: Test con Java/Maven
    needs: test-python
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install specific Chrome version
      run: |
        sudo apt-get update
        # Uninstall any existing versions of Chrome
        sudo apt-get remove -y google-chrome-stable
        # Install a specific version of Chrome (example: 129.0.0)
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f
        # Optionally, you can also specify a direct download link for a specific version
        # wget https://dl.google.com/linux/direct/google-chrome-stable_129.0.0-1_amd64.deb
        # sudo dpkg -i google-chrome-stable_129.0.0-1_amd64.deb

    - name: Install compatible ChromeDriver
      run: |
        # Get Chrome version
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)

        echo "Detected Chrome version: $CHROME_VERSION"
        echo "Detected major version: $MAJOR_VERSION"
        
        # Fetch compatible ChromeDriver version
        DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$MAJOR_VERSION")

        echo "Detected ChromeDriver version: $DRIVER_VERSION"

        # Check if DRIVER_VERSION is not empty
        if [ -z "$DRIVER_VERSION" ]; then
          echo "No compatible ChromeDriver version found for Chrome version: $CHROME_VERSION"
          exit 1
        fi
        
        # Download and install ChromeDriver
        wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv -f chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run Selenium tests
      run: mvn test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          google_screenshot.png
          test_result.pdf
          test_result.html