name: Run TEST Auto with Python / Java_Maven / Java_Gradle

on:
  push:
    branches:
      - feature-deployment
  pull_request:
    branches:
      - main

jobs:
  test-python:
    name: Test con Python
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate HTML report
      run: |
        pytest --html=report.html --self-contained-html
        pytest

    - name: Generate PDF report
      run: |
        python pdf_generator.py

    - name: Upload HTML & PDF reports
      uses: actions/upload-artifact@v3
      with:
        name: Python-reports
        path: |
          report.html
          report.pdf

  test-java-maven:
    name: Test con Java/Maven
    needs: test-python
    runs-on: windows-latest  # Cambiado de 'ubuntu-latest' a 'windows-latest'

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 8 (AdoptOpenJDK/Temurin)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install Google Chrome on Windows
      run: |
        choco install googlechrome -y
        choco install chromedriver -y

    - name: Install Maven on Windows
      run: |
        choco install maven -y
        mvn -version  # Verifica que Maven está correctamente instalado

    - name: Set up ChromeDriver path on Windows
      run: |
        $env:Path += ";C:\ProgramData\chocolatey\bin"
        echo "ChromeDriver path set"

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run Selenium tests
      run: mvn test

    - name: List surefire-reports directory
      run: |
        ls -R target/surefire-reports

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Java_Maven-results
        path: |
          google_screenshot.png
          test_result.pdf
          target/surefire-reports/

  test-java-gradle:
    name: Test con Java/Gradle
    needs: test-python && test-java-maven
    runs-on: windows-latest  # Cambiado de 'ubuntu-latest' a 'windows-latest'

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 8 (AdoptOpenJDK/Temurin)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install Google Chrome on Windows
      run: |
        choco install googlechrome -y
        choco install chromedriver -y

    - name: Set up ChromeDriver path on Windows
      run: |
        $env:Path += ";C:\ProgramData\chocolatey\bin"
        echo "ChromeDriver path set"

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: List surefire-reports directory
      run: |
        ls -R build/reports/tests/test/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Java_Gradle-results
        path: |
          build/reports/tests/test/